version: '3.3'

services:
  php-fpm:
    build:
      context: ./
      dockerfile: .docker/php-fpm.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    restart: always

  web:
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www
    links:
      - php-fpm
    ports:
      - '8050:80'